Rails.application.routes.draw do
  get 'heroes/Ana'
  get 'heroes/Bastion'
  get 'heroes/Brigitte'
  get 'heroes/DVa'
  get 'heroes/Doomfist'
  get 'heroes/Genji'
  get 'heroes/Hanzo'
  get 'heroes/Junkrat'
  get 'heroes/Lucio'
  get 'heroes/McCree'
  get 'heroes/Mei'
  get 'heroes/Mercy'
  get 'heroes/Moira'
  get 'heroes/Orisa'
  get 'heroes/Pharah'
  get 'heroes/Reaper'
  get 'heroes/Reinhardt'
  get 'heroes/Roadhog'
  get 'heroes/Soldier76'
  get 'heroes/Sombra'
  get 'heroes/Symmetra'
  get 'heroes/Torbjorn'
  get 'heroes/Tracer'
  get 'heroes/Widowmaker'
  get 'heroes/Winston'
  get 'heroes/Zarya'
  get 'heroes/Zenyatta'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'application#hello'
end
